@port = 3000
@url = http://localhost:{{port}}
@userId = 0001
@orderId = 1

###
GET {{url}}/health

###
GET {{url}}/api/menu

###
POST {{url}}/api/menu
content-type: application/json

{    
  "name": "熱拿鐵咖啡",
  "price": 65,
  "category": "飲料",
  "description": "使用義式濃縮搭配蒸煮鮮奶，奶泡綿密。",
  "imageUrl": "/imgs/menu/hot-latte.webp"
}

###
PATCH  {{url}}/api/menu/002
content-type: application/json

{    
  "changes": { "price": 70 },
  "reason": "測試調整價格"
}

###
DELETE  {{url}}/api/menu/006

###
GET {{url}}/api/orders

###
GET {{url}}/api/orders/current?userId={{userId}}

###
GET {{url}}/api/orders/history?userId={{userId}}

###
GET {{url}}/api/orders/{{orderId}}?userId={{userId}}

###
POST {{url}}/api/orders
content-type: application/json

{    
  "userId": "{{userId}}"
}

###
PATCH  {{url}}/api/orders/{{orderId}}
content-type: application/json

{    
  "userId": "{{userId}}",
  "itemId": "002-01",
  "qty": 3
}

###
POST {{url}}/api/orders/{{orderId}}/submit
content-type: application/json

{
  "userId": "{{userId}}"
}

###
POST {{url}}/api/auth/login
content-type: application/json

{
  "email": "demo@example.com",
  "password": "1234"
}
