CREATE EXTENSION IF NOT EXISTS "pgcrypto";--> statement-breakpoint
CREATE SCHEMA IF NOT EXISTS "bf_v10";--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "bf_v10"."user" (
  "id" text PRIMARY KEY NOT NULL,
  "name" text NOT NULL,
  "email" text NOT NULL,
  "email_verified" boolean DEFAULT false NOT NULL,
  "image" text,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  CONSTRAINT "user_email_unique" UNIQUE("email")
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bf_v10"."account" (
  "id" text PRIMARY KEY NOT NULL,
  "user_id" text NOT NULL,
  "account_id" text NOT NULL,
  "provider_id" text NOT NULL,
  "access_token" text,
  "refresh_token" text,
  "access_token_expires_at" timestamp,
  "refresh_token_expires_at" timestamp,
  "scope" text,
  "id_token" text,
  "password" text,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bf_v10"."session" (
  "id" text PRIMARY KEY NOT NULL,
  "user_id" text NOT NULL,
  "token" text NOT NULL,
  "expires_at" timestamp NOT NULL,
  "ip_address" text,
  "user_agent" text,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  CONSTRAINT "session_token_unique" UNIQUE("token")
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bf_v10"."verification" (
  "id" text PRIMARY KEY NOT NULL,
  "identifier" text NOT NULL,
  "value" text NOT NULL,
  "expires_at" timestamp NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);--> statement-breakpoint

INSERT INTO "bf_v10"."user" (
  "id", "name", "email", "email_verified", "image", "created_at", "updated_at"
)
SELECT "id", "name", "email", "email_verified", "image", "created_at", "updated_at"
FROM "bf_v9"."user"
ON CONFLICT ("id") DO NOTHING;--> statement-breakpoint
INSERT INTO "bf_v10"."account" (
  "id", "user_id", "account_id", "provider_id", "access_token", "refresh_token",
  "access_token_expires_at", "refresh_token_expires_at", "scope", "id_token",
  "password", "created_at", "updated_at"
)
SELECT
  "id", "user_id", "account_id", "provider_id", "access_token", "refresh_token",
  "access_token_expires_at", "refresh_token_expires_at", "scope", "id_token",
  "password", "created_at", "updated_at"
FROM "bf_v9"."account"
ON CONFLICT ("id") DO NOTHING;--> statement-breakpoint
INSERT INTO "bf_v10"."verification" (
  "id", "identifier", "value", "expires_at", "created_at", "updated_at"
)
SELECT "id", "identifier", "value", "expires_at", "created_at", "updated_at"
FROM "bf_v9"."verification"
ON CONFLICT ("id") DO NOTHING;--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "bf_v10"."menu_items" (
  "id" text PRIMARY KEY NOT NULL,
  "entity_id" text NOT NULL,
  "logical_id" text NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "name" text NOT NULL,
  "price" integer NOT NULL,
  "category" text NOT NULL,
  "description" text NOT NULL,
  "image_url" text NOT NULL,
  "is_current_version" boolean DEFAULT true NOT NULL,
  "supersedes" text,
  "change_reason" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "created_by" text
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bf_v10"."orders" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" text NOT NULL,
  "total" integer DEFAULT 0 NOT NULL,
  "status" text DEFAULT 'pending' NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  "submitted_at" timestamp with time zone
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bf_v10"."order_items" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "order_id" integer NOT NULL,
  "menu_item_id" text NOT NULL,
  "qty" integer NOT NULL
);--> statement-breakpoint

INSERT INTO "bf_v10"."menu_items" (
  "id", "entity_id", "logical_id", "version", "name", "price", "category",
  "description", "image_url", "is_current_version", "change_reason", "created_at",
  "created_by"
)
SELECT
  LPAD("id"::text, 3, '0') || '-01',
  gen_random_uuid()::text,
  LPAD("id"::text, 3, '0'),
  1,
  "name",
  "price",
  "category",
  "description",
  "image_url",
  true,
  'Migrated from bf_v9',
  now(),
  'migration'
FROM "bf_v9"."menu_items"
ON CONFLICT ("id") DO NOTHING;--> statement-breakpoint
INSERT INTO "bf_v10"."orders" (
  "id", "user_id", "total", "status", "created_at", "submitted_at"
)
SELECT "id", "user_id", "total", "status", "created_at", "submitted_at"
FROM "bf_v9"."orders"
ON CONFLICT ("id") DO NOTHING;--> statement-breakpoint
INSERT INTO "bf_v10"."order_items" (
  "id", "order_id", "menu_item_id", "qty"
)
SELECT
  "id",
  "order_id",
  LPAD("item_id"::text, 3, '0') || '-01',
  "qty"
FROM "bf_v9"."order_items"
ON CONFLICT ("id") DO NOTHING;--> statement-breakpoint

SELECT setval(
  pg_get_serial_sequence('"bf_v10"."orders"', 'id'),
  COALESCE((SELECT max("id") FROM "bf_v10"."orders"), 1),
  true
);--> statement-breakpoint
SELECT setval(
  pg_get_serial_sequence('"bf_v10"."order_items"', 'id'),
  COALESCE((SELECT max("id") FROM "bf_v10"."order_items"), 1),
  true
);--> statement-breakpoint

ALTER TABLE "bf_v10"."account" DROP CONSTRAINT IF EXISTS "account_user_id_user_id_fk";--> statement-breakpoint
ALTER TABLE "bf_v10"."session" DROP CONSTRAINT IF EXISTS "session_user_id_user_id_fk";--> statement-breakpoint
ALTER TABLE "bf_v10"."orders" DROP CONSTRAINT IF EXISTS "orders_user_id_user_id_fk";--> statement-breakpoint
ALTER TABLE "bf_v10"."order_items" DROP CONSTRAINT IF EXISTS "order_items_order_id_orders_id_fk";--> statement-breakpoint
ALTER TABLE "bf_v10"."order_items" DROP CONSTRAINT IF EXISTS "order_items_menu_item_fk";--> statement-breakpoint
ALTER TABLE "bf_v10"."menu_items" DROP CONSTRAINT IF EXISTS "menu_items_supersedes_menu_items_id_fk";--> statement-breakpoint

ALTER TABLE "bf_v10"."account"
  ADD CONSTRAINT "account_user_id_user_id_fk"
  FOREIGN KEY ("user_id") REFERENCES "bf_v10"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bf_v10"."session"
  ADD CONSTRAINT "session_user_id_user_id_fk"
  FOREIGN KEY ("user_id") REFERENCES "bf_v10"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bf_v10"."orders"
  ADD CONSTRAINT "orders_user_id_user_id_fk"
  FOREIGN KEY ("user_id") REFERENCES "bf_v10"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bf_v10"."order_items"
  ADD CONSTRAINT "order_items_order_id_orders_id_fk"
  FOREIGN KEY ("order_id") REFERENCES "bf_v10"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bf_v10"."order_items"
  ADD CONSTRAINT "order_items_menu_item_fk"
  FOREIGN KEY ("menu_item_id") REFERENCES "bf_v10"."menu_items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bf_v10"."menu_items"
  ADD CONSTRAINT "menu_items_supersedes_menu_items_id_fk"
  FOREIGN KEY ("supersedes") REFERENCES "bf_v10"."menu_items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "menu_items_entity_version_idx"
  ON "bf_v10"."menu_items" ("entity_id", "version");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "menu_items_logical_id_idx"
  ON "bf_v10"."menu_items" ("logical_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "menu_items_current_version_idx"
  ON "bf_v10"."menu_items" ("is_current_version")
  WHERE "is_current_version" = true;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "order_items_order_menu_idx"
  ON "bf_v10"."order_items" ("order_id", "menu_item_id");--> statement-breakpoint
CREATE OR REPLACE VIEW "bf_v10"."current_menu" AS
  SELECT * FROM "bf_v10"."menu_items" WHERE "is_current_version" = true;
