ALTER TABLE "bf_v10"."menu_items"
  ADD COLUMN IF NOT EXISTS "major_version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "bf_v10"."menu_items"
  ADD COLUMN IF NOT EXISTS "minor_version" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "bf_v10"."menu_items"
  ADD COLUMN IF NOT EXISTS "test_group" text DEFAULT 'default' NOT NULL;--> statement-breakpoint

UPDATE "bf_v10"."menu_items"
SET
  "major_version" = 1,
  "minor_version" = GREATEST("version" - 1, 0),
  "test_group" = COALESCE(NULLIF("test_group", ''), 'default')
WHERE "major_version" IS NULL
   OR "minor_version" IS NULL
   OR "test_group" IS NULL
   OR "test_group" = '';--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "bf_v10"."menu_display_order" (
  "logical_id" text PRIMARY KEY NOT NULL,
  "display_order" integer NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

INSERT INTO "bf_v10"."menu_display_order" ("logical_id", "display_order")
SELECT
  "logical_id",
  row_number() OVER (ORDER BY "logical_id")::integer
FROM (
  SELECT DISTINCT "logical_id"
  FROM "bf_v10"."menu_items"
  WHERE "is_current_version" = true
) current_items
ON CONFLICT ("logical_id") DO NOTHING;--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "bf_v10"."promotions" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "menu_item_logical_id" text NOT NULL,
  "discount_type" text DEFAULT 'amount' NOT NULL,
  "discount_value" integer NOT NULL,
  "starts_at" timestamp with time zone NOT NULL,
  "ends_at" timestamp with time zone NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL
);--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "menu_display_order_display_order_idx"
  ON "bf_v10"."menu_display_order" ("display_order");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "promotions_menu_item_logical_id_idx"
  ON "bf_v10"."promotions" ("menu_item_logical_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "promotions_active_window_idx"
  ON "bf_v10"."promotions" ("is_active", "starts_at", "ends_at");--> statement-breakpoint
